### ISSUE TITLE
error using library  - cb is not a function

### ISSUE THREAD

**Issue by ORESoftware** [nicksrandall/inquierer-directory#13] opened 2016-11-04 02:33 UTC
got this just now
```

SFOC02Q106HG8WM:suman t_millal$ node lib/interactive/index2.js 
? Where you like to put this component? (Use arrow keys)
? Where you like to put this component? default-conf-files
(Use "/" key to search this directory)


readline.js:982
            throw err;
            ^

TypeError: cb is not a function
    at module.exports (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/node_modules/run-async/index.js:23:5)
    at Prompt.filter (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/node_modules/inquirer/lib/prompts/base.js:128:3)
    at Prompt.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/node_modules/inquirer/lib/prompts/base.js:56:10)
    at Prompt.onSubmit (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/index.js:234:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/t_millal/WebstormProjects/oresoftware/suman/node_modules/inquirer-directory/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)

```

**Comment by ORESoftware** [comment] 2016-11-07 07:22
Please God, looking for answers

**Comment by amwmedia** [comment] 2016-11-07 11:41
`plop` v1.6.0 upgrades to the inquirer 1.x library. That is likely the cause of this error because `inquirer-directory` is using pre-v1. Until the dependency is updated in this repo, a temporary fix could be to change your plop dependency to specifically target plop 1.5.0.

**Comment by amwmedia** [comment] 2016-11-07 11:48
ah, I just realized that you are not likely using this with plop. My mistake.

**Comment by ORESoftware** [comment] 2016-11-07 22:45
np, I don't think I am using plop, but do you see the same error that I do when running this lib?

**Comment by amwmedia** [comment] 2016-11-08 15:12
strangely I'm not right now. Plop uses the latest inquirer now and I was expecting the plugin to break, however it seems to be ok.

**Comment by nicksrandall** [comment] 2016-11-08 20:09
fixed via https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0

**Closed as completed by nicksrandall** 2016-11-08 20:09 UTC

**Comment by ORESoftware** [comment] 2016-11-08 20:54
thanks! :) 🎱
